add zoom message support
Sorunome/matrix-slack-parser pull request #7
Opened 2020-05-10 18:37 UTC by ericmigi

now shows zoom call messages

2020-05-10 19:08 UTC, Sorunome commented
Is that a normal, documented block?

2020-05-10 19:09 UTC, Sorunome requested changes
Otherwise looks good!

2020-05-10 19:09 UTC, Sorunome commented on src/slackmessageparser.ts
> +					return `<a href="${join_url}">${content}</a>`;
please `escapeHtml()` your variables ^^ name and join_url aren't neecessarily escaped

2020-05-11 16:06 UTC, ericmigi commented
looks good, thanks for reviewing!

2020-05-12 18:25 UTC, ericmigi commented
anything else I need to do?

2020-05-12 18:31 UTC, Sorunome commented
fix the requested changes? (maybe you forgot to push?)

Am 12. Mai 2020 20:26:07 MESZ schrieb Eric Migicovsky <notifications@github.com>:
>anything else I need to do?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Sorunome/matrix-slack-parser/pull/7#issuecomment-627514073

2020-05-14 21:57 UTC, closed without merging